version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - pip install gitleaks
      - (cd infra && npm ci --no-progress)

  build:
    commands:
      - echo "Running linting and type checking..."
      - (cd infra && npm run build || echo "TypeScript compilation check")
      - echo "Scanning for secrets..."
      - gitleaks detect --source . --no-banner --exit-code 0 || echo "Secret scan completed"

